In [40]:
# pip install -U tensorflow --user

In [41]:
import cv2
import numpy as np
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import time
import os
# from IPython.core.interactiveshell import InteractiveShell
# InteractiveShell.ast_node_interactivity = "all"

In [42]:
video = cv2.VideoCapture(0)
frame_width = int(video.get(3))
frame_height = int(video.get(4))
out = cv2.VideoWriter('turns.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 8, (frame_width,frame_height))
front_det = cv2.CascadeClassifier(r'H:\Python\Data\Haar_cascade\frontalFace10\haarcascade_frontalface_alt2.xml')
prof_det = cv2.CascadeClassifier(r'H:\Python\Data\Haar_cascade\profileFace10\haarcascade_profileface.xml')
font = cv2.FONT_HERSHEY_DUPLEX

maskNet = load_model("mask_detector.model")
prototxtPath = r"face_detector\deploy.prototxt"
weightsPath = r"face_detector\res10_300x300_ssd_iter_140000.caffemodel"
faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)

In [43]:

while True:
    ret, frame = video.read()
    frame_res = cv2.resize(frame,(244,244))
    frame_res = img_to_array(frame_res)
    frame_res = preprocess_input(frame_res)
    frame_res = np.expand_dims(frame_res, axis=0)
    pred = maskNet.predict(frame_res, batch_size=32)
    pred = np.reshape(pred,(2,1))
    print(pred)
    (mask, withoutMask) = pred
    label = "Mask" if mask > withoutMask else "No Mask"
    color = (0, 255, 0) if label == "Mask" else (0, 0, 255)
    
    
    front_faces_l =front_det.detectMultiScale(
        frame,     
        scaleFactor=1.2,
        minNeighbors=5,     
        minSize=(20, 20)
    )
    
    prof_faces_l =prof_det.detectMultiScale(
        frame,     
        scaleFactor=1.2,
        minNeighbors=5,     
        minSize=(20, 20)
    )
    
    frame_rev = cv2.flip(frame, 1)
    front_faces_r = front_det.detectMultiScale(
        frame_rev,     
        scaleFactor=1.2,
        minNeighbors=5,     
        minSize=(20, 20)
    )    
    prof_faces_r = prof_det.detectMultiScale(
        frame_rev,     
        scaleFactor=1.2,
        minNeighbors=5,     
        minSize=(20, 20)
    )
    
    if front_faces_l!=():
        for (x,y,w,h) in front_faces_l:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
            cv2.putText(frame, label, (x, y),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)
           

    if front_faces_r!=():
        for (x,y,w,h) in front_faces_r:
            cv2.rectangle(frame_rev,(x,y),(x+w,y+h),(0,255,0),2)
            frame =  cv2.flip(frame_rev, 1)
            cv2.putText(frame, label, (x, y),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)
            
            
    if prof_faces_l!=():
            for (x,y,w,h) in prof_faces_l:
                cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),2)            
                cv2.putText(frame, 'OBJECT TURNED!!!', (x + 6, y - 6), font, 0.5, (0, 0, 255), 1)
                out.write(frame)
 
    if prof_faces_r!=():
        for (x,y,w,h) in prof_faces_r:
            cv2.rectangle(frame_rev,(x,y),(x+w,y+h),(0,0,255),2)
            frame =  cv2.flip(frame_rev, 1)
            cv2.putText(frame, 'OBJECT TURNED!!!', (x + 6 + w, y - 6), font, 0.5, (0, 0, 255), 1)
            out.write(frame)
            
    if front_faces_l==() and front_faces_r==() and prof_faces_l==() and prof_faces_r==():
        cv2.putText(frame, 'NO FACE!!!',(50,50), font, 0.5, (0, 0, 255), 1)
        out.write(frame)
        
    cv2.imshow('camera',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
video.release()
out.release()
cv2.destroyAllWindows() 



[[0.00360978]
 [0.99639016]]
[[0.01045441]
 [0.9895455 ]]

<ipython-input-43-3cfd697f3c22>:43: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if front_faces_l!=():
<ipython-input-43-3cfd697f3c22>:50: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if front_faces_r!=():
<ipython-input-43-3cfd697f3c22>:71: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if front_faces_l==() and front_faces_r==() and prof_faces_l==() and prof_faces_r==():



[[0.01050487]
 [0.9894951 ]]
[[0.00429039]
 [0.99570954]]
[[0.01175283]
 [0.9882472 ]]
[[0.00714559]
 [0.9928544 ]]
[[0.0036387]
 [0.9963613]]
[[0.00712639]
 [0.99287355]]
[[0.01680376]
 [0.98319626]]
[[0.01245554]
 [0.98754454]]
[[0.00709336]
 [0.9929067 ]]


<ipython-input-43-3cfd697f3c22>:64: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if prof_faces_r!=():


[[0.00502602]
 [0.994974  ]]
[[0.00351814]
 [0.9964818 ]]
[[0.00417014]
 [0.9958299 ]]
[[0.01179651]
 [0.98820347]]
[[0.00508705]
 [0.99491286]]
[[0.00374921]
 [0.9962508 ]]
[[0.00307256]
 [0.99692744]]
[[0.00388925]
 [0.99611074]]
[[0.00362551]
 [0.9963744 ]]
[[0.00330426]
 [0.99669576]]
[[0.00384898]
 [0.9961511 ]]
[[0.0040241]
 [0.9959759]]
[[0.004385]
 [0.995615]]
[[0.00480722]
 [0.99519277]]
[[0.00810437]
 [0.9918956 ]]
[[0.00607956]
 [0.99392045]]
[[0.00341987]
 [0.9965802 ]]
[[0.00482886]
 [0.9951711 ]]
[[0.00245269]
 [0.9975473 ]]
[[0.836677  ]
 [0.16332299]]
[[0.8948749 ]
 [0.10512514]]
[[0.576519  ]
 [0.42348093]]
[[0.7291072 ]
 [0.27089283]]
[[0.9953105 ]
 [0.00468954]]
[[0.9444093 ]
 [0.05559072]]
[[0.87003464]
 [0.12996529]]
[[0.83147424]
 [0.1685258 ]]
[[0.787747  ]
 [0.21225299]]
[[0.91494775]
 [0.08505224]]
[[0.92946297]
 [0.07053702]]
[[0.98480093]
 [0.01519912]]
[[0.96700525]
 [0.03299472]]
[[0.9824709 ]
 [0.01752905]]
[[0.9761514]
 [0.0238486]]
[[0.9858278 ]
 [0.0141

<ipython-input-43-3cfd697f3c22>:58: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if prof_faces_l!=():


[[9.994808e-01]
 [5.192460e-04]]
[[9.9981683e-01]
 [1.8321942e-04]]
[[9.9964941e-01]
 [3.5054685e-04]]
[[9.991953e-01]
 [8.047333e-04]]
[[9.9963093e-01]
 [3.6902368e-04]]
[[9.9958366e-01]
 [4.1636289e-04]]
[[9.9959868e-01]
 [4.0133143e-04]]
[[9.994273e-01]
 [5.727109e-04]]
[[9.9960655e-01]
 [3.9345218e-04]]
[[9.9924719e-01]
 [7.5285375e-04]]
[[0.9984106 ]
 [0.00158942]]
[[0.9897535 ]
 [0.01024659]]
[[0.93207085]
 [0.06792918]]
[[0.98871917]
 [0.01128084]]
[[0.9669808 ]
 [0.03301917]]
[[0.97778374]
 [0.02221625]]
[[0.9725303 ]
 [0.02746969]]
[[0.95003676]
 [0.04996322]]
[[0.96711105]
 [0.032889  ]]
[[0.8820562]
 [0.1179438]]
[[0.9882135 ]
 [0.01178651]]
[[0.9976622 ]
 [0.00233785]]
[[0.9498655 ]
 [0.05013451]]
[[0.9584034]
 [0.0415966]]
[[0.9943521 ]
 [0.00564791]]
[[0.9841204 ]
 [0.01587956]]
[[0.9825613 ]
 [0.01743878]]
[[0.9689086 ]
 [0.03109147]]
[[0.9843875 ]
 [0.01561252]]
[[0.9933802 ]
 [0.00661983]]
[[9.9977154e-01]
 [2.2852630e-04]]
[[9.9961203e-01]
 [3.8805135e-04]]
[[0.994298